### ISSUE TITLE
contributorsにcamcam_lemon追加

### ISSUE THREAD

**Issue by tyankatsu0105** [tyankatsu0105/cz-format-extension#15]
https://docs.npmjs.com/files/package.json#people-fields-author-contributors

```
{
      "name": "camcam_lemon",
      "url": "https://github.com/camcam-lemon"
    }
```

的なのをpackage.jsonに追加する

**Comment by tyankatsu0105** [comment]
@camcam-lemon 
自分でかけるようであれば`package.json`に追記してもらえると🙏

**Comment by camcam-lemon** [comment]
@tyankatsu0105 
自分で追加しときやす

**Comment by tyankatsu0105** [comment]
気が向いたらやって😤

**Comment by tyankatsu0105** [comment]
@camcam-lemon 
thank you for your commit!!👍
