### ISSUE TITLE
out babel in webpack

### ISSUE THREAD

**Issue by tyankatsu0105** [tyankatsu0105/cz-format-extension#19]
babelいらんかもしれん
webpackでsrcのソースを圧縮したいけどどうしたら良いのかわからない・・・

**Comment by tyankatsu0105** [comment]
@camcam-lemon 
src内のファイルを圧縮してlibに排出したいんですけど、
何か案ありますか？？🙏

**Comment by camcam-lemon** [comment]
@tyankatsu0105 
圧縮って`uglifyjs-webpack-plugin`かましたいってことですかね？
モジュールとして提供するものは圧縮はしない方がいいですよ。  
圧縮しちゃうと、node_modules内から直接参照する時に誰も理解できなくなっちゃうので。  
lodashしかりlongestしかり、npmモジュールはBabelやwebpackでトランスパイルするだけのものが多いです。

元の`cz-conventional-changelog`をnode_modules内で確認しましたけど、こいつも
ES5にしてるだけだったので、必要ないかなと。

**Comment by tyankatsu0105** [comment]
@camcam-lemon 
babelは必要ですかね？？

**Comment by camcam-lemon** [comment]
@tyankatsu0105 
昔のnodeもサポートするなら必要ですね！
ただ、nodeのバージョンを昔のものに固定してる人たちってかなり少数人数なので
あってもなくても問題ないと思うんですよね。

**Comment by camcam-lemon** [comment]
でもまぁ、async/awaitを使うならあった方がいいかもしれない・・・

**Comment by tyankatsu0105** [comment]
なるほどぉ
じゃあbabelだけはやっとくか

**Comment by tyankatsu0105** [comment]
現状のままでいいのでclose
