### ISSUE TITLE
eslint-config-airbnb-baseを採用する

### ISSUE THREAD

**Issue by camcam-lemon** [tyankatsu0105/cz-format-extension#7]
## 概要
- eslint-config-airbnb-baseを依存モジュールに追加
- 関係のない依存モジュールを削除
  - eslint-config-airbnb
  - eslint-plugin-jsx-a11y
  - eslint-plugin-react

## なぜ変更するのか
Reactのプロジェクトではないので、eslint-config-airbnbは必要ない。  
React固有の設定のみを削除したeslint-config-airbnb-baseにするのが適切。

**Comment by tyankatsu0105** [comment]
こんのあったのかー
